module.exports = {
  apps: [
    {
      name: "web",
      script: "server.js",
      cwd: "/var/www/shardtown",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/shardtown/web.err.log",
      out_file: "/var/log/shardtown/web.out.log",
      merge_logs: true,
    },
    {
      name: "shardguard",
      script: "Shardtown/sharder.js",
      cwd: "/var/www/shardtown",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/shardtown/shardguard.err.log",
      out_file: "/var/log/shardtown/shardguard.out.log",
      merge_logs: true,
    },
    {
      name: "shard",
      script: "Shard/sharder.js",
      cwd: "/var/www/shardtown",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/shardtown/shard.err.log",
      out_file: "/var/log/shardtown/shard.out.log",
      merge_logs: true,
    },
  ],
};
